### ISSUE TITLE
could not open dynamic library located at libkdb_path when starting radiusd

### ISSUE THREAD

**Issue by mehdibo** [Martichou/freeradius-server#2]
Hello!

When running `/usr/local/sbin/radiusd -X` I get

```
  # Instantiating module "mschapv2_kerberos" from file /usr/local/etc/raddb/mods-enabled/mschapv2_kerberos
rlm_mschapv2_kerberos (mschapv2_kerberos): using internal authentication
/usr/local/etc/raddb/mods-enabled/mschapv2_kerberos[11]: could not open dynamic library located at libkdb_path
/usr/local/etc/raddb/mods-enabled/mschapv2_kerberos[11]: Instantiation failed for module "mschapv2_kerberos"
```

The libkdb_path value in the config file is `libkdb_path = /usr/local/lib/libkdb5.so`

And the file `/usr/local/lib/libkdb5.so` exists
```
#> ls -l /usr/local/lib/libkdb5.so
lrwxrwxrwx 1 root root 14 Feb  1 12:29 /usr/local/lib/libkdb5.so -> libkdb5.so.9.0
```

Any solution please?

**Comment by mehdibo** [comment]
A clean reinstall of Debian solved this, but now having another error:
```
/usr/local/etc/raddb/mods-enabled/mschapv2_kerberos[11]: krb5_ldap_db_init() function failed
/usr/local/etc/raddb/mods-enabled/mschapv2_kerberos[11]: Instantiation failed for module "mschapv2_kerberos"
````

**Comment by Martichou** [comment]
Hey !

Sorry for the late answer. Two things here:

1) I'm not maintaining this repo anymore, it has been forked by the 42Network and as I believe you're using this repo for a 42 School, you may want to ask them ;) 
2) Regarding the issue, you need to use the custom krb5 version on my Github as well (at least on the freeRadius server to link the needed libs), check it out here: https://github.com/Martichou/krb5.

And if you have access to the 42Network Staff's Slack (42World), I've once posted an ansible script that would setup a new host for freeRadius with everything needed. 

ps: https://github.com/42School/freeradius-server
